name: Run Daily ETF Email

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 2:30 PM IST (9:00 AM UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASS: ${{ secrets.PASS }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install yfinance pandas numpy

    - name: Run alert script
      run: python alert_script.py
